module.exports = {
  apps: [
    {
      name: 'mining-user-api',
      script: 'dist/apps/user-api/main.js',
      cwd: __dirname,
      exec_mode: 'cluster',
      instances: 3,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        USER_API_PORT: 3000,
      },
      error_file: './logs/user-api-error.log',
      out_file: './logs/user-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'mining-admin-api',
      script: 'dist/apps/admin-api/main.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        ADMIN_API_PORT: 3001,
      },
      error_file: './logs/admin-api-error.log',
      out_file: './logs/admin-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'mining-worker',
      script: 'dist/apps/worker/main.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
  ],
};
